### ISSUE TITLE
Issue on mac M1

### ISSUE THREAD

**Issue by kartikhegadi** [TimKong21/Polyp-Segmentation#1]
While installing dependencies. ERROR
<img width="1439" alt="Screenshot 2024-03-30 at 11 30 53 AM" src="https://github.com/TimKong21/Polyp-Segmentation/assets/67619115/f3ff0c56-9574-45f1-ac19-d2de2fe68d19">
any other methord?

**Comment by TimKong21** [comment]
Hi Kartik,

To address the installation issues on Mac M1, you should use Python >= 3.7 and < 3.11. Specifically for Mac M1, setting up a virtual environment with Python 3.8 is recommended. After setting up Python 3.8, you can try reinstalling the dependencies.

If issues persist, consider removing the explicit version numbers in the requirements.txt to let pip choose compatible versions for your system.

As a note, I'm developing this project on Windows with Python 3.10.11, which works well for me, but I do not use a Mac for testing.

For the Mac M1 architecture, ensure to install the ARM-compatible TensorFlow (`tensorflow-macos`).

Hope this helps.

**Comment by TimKong21** [comment]
Hi Kartik,

To address the installation issues on Mac M1, you should use Python >= 3.7 and < 3.11. Specifically for Mac M1, setting up a virtual environment with Python 3.8 is recommended. After setting up Python 3.8, you can try reinstalling the dependencies.

If issues persist, consider removing the explicit version numbers in the requirements.txt to let pip choose compatible versions for your system.

As a note, I'm developing this project on Windows with Python 3.10.11, which works well for me, but I do not use a Mac for testing.

For the Mac M1 architecture, ensure to install the ARM-compatible TensorFlow (`tensorflow-macos`).

Hope this helps.

**Comment by kartikhegadi** [comment]
Yes It helped me!! 

Hi TimKong21,

**_Thank you_** for your detailed guidance! I followed your instructions and successfully set up Python 3.8 on my **Mac M1**. After reinstalling the dependencies and ensuring compatibility with **ARM architecture**, everything seems to be working smoothly now. Additionally, I've forked the project and made necessary changes to ensure compatibility for all Mac users. Your assistance has been invaluable in resolving the installation issues.

<img width="1330" alt="Screenshot 2024-04-07 at 10 38 20 AM" src="https://github.com/TimKong21/Polyp-Segmentation/assets/67619115/73051f28-cd1f-43ce-bdc0-97da5d78f9ac">



**review** --> 
The uploaded image is displayed as the first.
The segmented mask appears as the second.
However, the third display, representing the detected image, is not showing correctly.
if any comments on this you can give suggestions @TimKong21 

Best regards,
**Kartik**

**Comment by TimKong21** [comment]
Hi Kartik,

Thank you for taking the time to adapt the project for Mac users.

Regarding your review, the current implementation of the Polyp Segmentation Tool is designed to display only two main elements for each uploaded image: the original image and the predicted segmentation mask. There isn't a third display for a "detected image" in the version you've worked with. If you're referring to an overlay of the segmentation mask on the original image, that feature hasn't been implemented yet.

**Comment by kartikhegadi** [comment]
Okay , all the best @TimKong21
